### ISSUE TITLE
Integration with Distrobuilder.

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [pieroproietti/penguins-eggs#172]
https://github.com/lxc/distrobuilder

**Comment by pieroproietti** [comment]
brain overflow! :-p

**Comment by OpenOS-Project-Creator-Founder** [comment]
> brain overflow! :-p

The end goal is to create an LXC/LXD image of the Distro from the squashfs eggs makes.

Also, to allow packaging & configuring the guest of cloned host system into the host system so that there is a developer environment ready to go out-of-the-box. 

This would also allow for the guest system to be used for other scenarios as well.

Does this make sense?

-----------------------------------------------------------------_________________________________________
-----------------------------------------------------------------

L'obiettivo finale è creare un'immagine LXC/LXD del Distro dalle uova di zucca.

 Inoltre, per consentire l'impacchettamento e la configurazione del guest del sistema host clonato nel sistema host in modo che ci sia un ambiente di sviluppo pronto per l'uso immediato.

 Ciò consentirebbe anche di utilizzare il sistema guest anche per altri scenari.

 Questo ha senso?

**Comment by OpenOS-Project-Creator-Founder** [comment]
https://github.com/canonical/workshops

**Comment by OpenOS-Project-Creator-Founder** [comment]
Piero...

https://github.com/lxc/distrobuilder/issues/682#issuecomment-1430918411

**Comment by OpenOS-Project-Creator-Founder** [comment]
Also this.


https://github.com/lxc/distrobuilder/issues/685#issuecomment-1430923173
