### ISSUE TITLE
Pacstall Build...?

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [pieroproietti/penguins-eggs#180]
https://pacstall.dev/

https://github.com/pacstall/pacstall

[ ENGLISH ]

The AUR Ubuntu never had

Pacstall is the AUR Ubuntu wishes it had. It takes the concept of AUR and puts a spin on it, making it easier to install programs without scouring github repos and the likes.

Features
Supports binary, git, appimage, building and .deb packages
Accelerated package download using axel (optional)
During upgrades, you always get the latest build off of the latest commit from the developer for -git packages. No need to wait for the pacscript maintainer to update the script!
Ability to install programs from multiple repositories
Ability to track Pacstall updates from any fork/branch easily
Completions available for bash (ZSH), and fish

[ ITALIAN ]

L'AUR Ubuntu non l'ha mai avuto

 Pacstall è l'AUR che Ubuntu vorrebbe avere.  Prende il concetto di AUR e ci dà una svolta, rendendo più semplice l'installazione di programmi senza setacciare repository github e simili.

 L'elenco dei pacchetti disponibili è disponibile qui.

Caratteristiche
 Supporta pacchetti binari, git, appimage, building e .deb
 Download accelerato del pacchetto tramite axel (opzionale)
 Durante gli aggiornamenti, ottieni sempre l'ultima build dall'ultimo commit dallo sviluppatore per i pacchetti -git.  Non c'è bisogno di aspettare che il manutentore di pacscript aggiorni lo script!
 Possibilità di installare programmi da più repository
 Possibilità di monitorare facilmente gli aggiornamenti di Pacstall da qualsiasi fork/branch
 Completamenti disponibili per bash (ZSH) e fish

The list of available packages can be found here. / L'elenco dei pacchetti disponibili è disponibile qui.

https://pacstall.dev/packages?page=0&size=25&sortBy=default&sort=asc&filter=&filterBy=name

**Comment by pieroproietti** [comment]
I tried pacstall on a Ubuntu 22.04 customized version colibri, the result was exellent. Unfortunately before I tried it on Debian bullseye and bookworm version, here there is a problem becouse seem pacstall is addressed mostly to ubuntu (use zstd compression).

The project in all the ways is quite interesting, I will follow it.

**Comment by pieroproietti** [comment]
I just find anothere package manager inspired by Arch, it's called [makedeb](https://github.com/makedeb/makedeb) and seem to work with Debian bullseye too.

**Comment by Henryws** [comment]
> I tried pacstall on a Ubuntu 22.04 customized version colibri, the result was exellent. Unfortunately before I tried it on Debian bullseye and bookworm version, here there is a problem becouse seem pacstall is addressed mostly to ubuntu (use zstd compression).
> 
> The project in all the ways is quite interesting, I will follow it.

We don't use zstd in Pacstall.
