### ISSUE TITLE
ditch penguins eggs and look for something better

### ISSUE THREAD

**Issue by claudemods** [pieroproietti/penguins-eggs#332]
ditched penguins-eggs and found something better
hello stefano perri and piero proietti currently happily in my bed at the moment i found some on going issues with current isos it may not be all on your sourceforge but i can certainly talk for the current gnome. and arch albotros eggs and that these people https://www.penguins-eggs.com  where the ones to confirm they dont work after i tested the current albotros arch eggs iso and the gnome eggs iso

**Comment by pieroproietti** [comment]
Claudemods reminds me of Claude Monet a great artist, I once saw one of his exhibitions here in Rome, one of the best memories of my school days, the first field trip.

Don't lapse into such bad thoughts with such a nice nickname, honor it.
