### ISSUE TITLE
Why Wont It Save The Current Wallpaper

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [pieroproietti/penguins-eggs#355]
Hey I'm New To Penguins Eggs I Used It For An OS Im Developing But Please PLEASE Add A Feature Where you can save the current wallpaper as the main wallpaper

**Comment by pieroproietti** [comment]
Hi @GuestSneezeOSDev 

that you mean exists already! `sudo eggs tools skel` 

cheers

**Comment by GuestSneezeOSDev** [comment]
Thank's @pieroproietti Your Projects Is Actually Amazing. I Hope You Continue Your Projects
