### ISSUE TITLE
ISO Won't Boot

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [pieroproietti/penguins-eggs#357]
Yes You  May Remember Me I Am The Person Who asked For `sudo eggs tools skel`
Recently I Created An ISO With This Command `sudo eggs produce --basename GUESTSNEEZEOS --max` It Took A Few 30 Minutes But When It Finished I Saw That There Was NO `xorriso` Issues Then I Put It Into BalenaEtcher I Waited A While Then I Booted It Into My Old Laptop From 2014 (UEFI). I Installed It With `Text Mode` Since I Did Not Put Calamares I Booted It It Said `Press Any Key To Reboot` I Clicked Enter It Rebooted With An Error Saying `Not A Valid UEFI 64 BIT OS`

**Comment by pieroproietti** [comment]
Can you disabile UEFInsecurity boot?
