### ISSUE TITLE
Where is the source code of my iso

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [pieroproietti/penguins-eggs#358]
Is it the ovarium or iso folder?

**Comment by pieroproietti** [comment]
mmm, source code of your ISO?

if you mean your original work it's just on your ISO, if you mean eggs code, it's just this repository.

in ovarium there are just same scripts produced by eggs you can use to rebuild your ISO, this let you to editing your ISO before to be enclosed on a live image by xorriso or genisoimage. 

On ISO there is your full ISO, all the files will enclosed on ISO image. Along on this files there is filesystemfs.squashfs a compressed file, who is the copy of your system, to refresh this file with scripts, from /home/eggs/ovarium,
![ovarium](https://github.com/pieroproietti/penguins-eggs/assets/958613/27f0c9b9-68a9-4a58-80e2-ead2f32e0a05)

**Comment by GuestSneezeOSDev** [comment]
thanks
